### ISSUE TITLE
Optimise Codespace screen real estate

### ISSUE THREAD

**Issue by inglesp** [opensafely/ehrql-tutorial#16]
The default Codespace screen layout involves 

Specifically, we should if possible:

* hide the terminal
* hide the code outline
* make the code explorer as narrow as possible

Additionally, we should enable wordwrap.  This may necessitate re-flowing the comments in quiz.py.

**Comment by rebkwok** [comment]
It looks like changing the size of the code explorer (the VS Code workbench sidebar) is not currently possible: there's a [ticket](https://github.com/microsoft/vscode/issues/158603) for setting default sizes, so it might be possible in future.

I also can't find a way to close/hide the devcontainer terminal on startup. From [this issue](https://github.com/microsoft/vscode-remote-release/issues/4537) I think it might not yet be possible, but has been requested. (Note that's only related to the postCreate command; if you've previously closed the terminal and you restart the codespace, it won't open it again).

However, starting a codespace does something different, and opens a terminal with a "Welcome to codespaces" message. It also doesn't seem to be easy to [stop that from displaying](https://github.com/orgs/community/discussions/43534).  The research-template codespaces overrides this to show a custom OpenSAFELY message.  I think our best option is to do the same for the tutorial, with a custom terminal message that has a link to the tutorial in the docs and a note that you don't need the terminal panel and how to close it.

**Comment by inglesp** [comment]
All sounds reasonable!
